# Generated by Django 2.2.6 on 2019-10-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20191023_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
