# Generated by Django 2.2.6 on 2019-10-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20191023_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Author image'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='credit_card_number',
            field=models.BigIntegerField(verbose_name='Number credit card '),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.BigIntegerField(verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
